name: my_packages
version: 0.0.1
homepage: https://www.instagram.com/code.r17
description: A new Flutter package project.
repository: https://github.com/DobelD/my_packages.git
environment: 
  sdk: '>=2.19.6 <3.0.0'
  flutter: '>=1.17.0'

dependencies: 
  flutter_screenutil: 5.7.0
  flutter_svg: 2.0.5
  google_fonts: 4.0.4
  equatable: 2.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/svg/

